name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '16.13.2'

      - name: Install and Build 🔧
        run: |
          cd dindin
          npm ci
          npm run build
          cd ..
          cd Discord
          npm ci
          npm run build
          cd ..
          mkdir build
          mkdir build/fr
          mkdir build/fr/Discord
          cp -a dindin/dist/. build
          cp -a Discord/dist/. build/fr/Discord
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: dist # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
